### ISSUE TITLE
requestID middleware should entertain `X-Request-ID` along with `Request-ID` 

### ISSUE THREAD

**Issue by chinmayb** [infobloxopen/atlas-app-toolkit#170]
Currently NGINX controller accepts `X-Request-ID` and auto generates an ID . Internal components who use requestID middleware looks for `Request-ID`. So the nginx requestID gets lost and new requestID gets propagated. 

Proposals
* make changes in nginx to accept `Request-ID` header
or
* Modify the middleware to accept just  ` X-Request-ID` or both.

**Comment by kd7lxl** [comment]
It will be easier to modify the nginx config to accept `Request-ID`. I am working on a PR for this.

**Comment by Evgeniy-L** [comment]
@chinmayb, @kd7lxl, this was investigated previously and there is a document on how to populate [Request Id At Nginx level](https://docs.google.com/document/d/1mP3AjZlbivh9ogli8ioThGkIll-lnFR4Bxh2Zc2cUmE/edit#heading=h.gf4dcsoy4w8y).

`request-id` middleware works on gRPC level and tries to extract Request-Id from gRPC metadata. See:
https://github.com/infobloxopen/atlas-app-toolkit/blob/master/requestid/requestid.go#L37
https://github.com/infobloxopen/atlas-app-toolkit/blob/master/gateway/header.go#L15

Headers that come from REST need to be translated to gRPC metadata. This is done by [DefaultHeaderMatcher](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/mux.go#L64). The problem here is that headers like `Request-ID` or `X-Request-ID` are not translated by default. Headers translation can solved like [this](https://github.com/infobloxopen/atlas-cli/pull/34/files).

Following the [Request Id At Nginx level](https://docs.google.com/document/d/1mP3AjZlbivh9ogli8ioThGkIll-lnFR4Bxh2Zc2cUmE/edit#heading=h.gf4dcsoy4w8y) doc we will be able to populate `Grpc-Metadata-Request-Id` header which will be translated to `Request-ID` into gRPC metadata by [DefaultHeaderMatcher](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/mux.go#L64). This way we will not need any changes for existing services. In a similar way we will be able to add other headers at Nginx level if needed.

**Comment by drewwells** [comment]
Request-ID is not a standard HTTP header. Toolkit should support the very common header X-Request-ID. This ID is not just for nginx, it's used by many proxies and middleware logging applications to trace requests through server stacks. We do not want to modify every possible middleware to support our non-standard Header which most likely will break future applications when a Request-ID standard is defined.

We should deprecate, but continue to support Request-ID while adding support and updating documentation for X-Request-ID. At the next major release, we can remove support for Request-ID.

https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_response_fields

**Comment by Calebjh** [comment]
Fixed in #197
